services:
  - type: web
    name: serhui-proxy
    env: node
    buildCommand: npm install
    startCommand: node server-vless.js
    healthCheckPath: /health
    instanceType: free
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
      - key: VLESS_UUID
        value: 7ec6d45a-9ef0-4418-8c92-f076448e9c09
      - key: VLESS_FLOW
        value: xtls-rprx-vision
    disk:
      mountPath: /data
      sizeGB: 1
